# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'ORB' do
  # Pods for ORB
  pod 'NMapsMap'
end

target 'ORB_Dev' do
  # Pods for ORB_Dev
  pod 'NMapsMap'
end

target 'Offroad-iOSTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'Offroad-iOSUITests' do
  inherit! :search_paths
  # Pods for testing
end
