# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Offroad-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Offroad-iOS
  pod 'NMapsMap'

  target 'Offroad-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Offroad-iOSUITests' do
    # Pods for testing
  end

end
